server:
  port: 9096
  management:
    server:
      port: 9096
    endpoints:
      web:
        exposure:
          include:
            - health
            - info
            - metrics
    endpoint:
      health:
        show-details: always
  ssl:
    enabled: false
#    key-store-type: PKCS12
#    key-store: certs/mcp-server-keystore.p12
#    key-store-password: ""
#    key-alias: mcp-server
#    trust-store-type: PKCS12
#    trust-store: certs/mcp-clients-truststore.p12
#    trust-store-password: ""
#    client-auth: need  # need | want | none

crossover:
  api:
    base-url: http://localhost:8008/
    timeout: 30000
    apiKey: ${PROM_CROSSOVER_API_KEY}

logging:
  level:
    org.springframework.web.client: DEBUG
    org.springframework.http: DEBUG
    ru.sber.apm.aipay.ratatouille.service.p2pcrypto: DEBUG

link:
  api:
    base-url: http://localhost:8018/
    timeout-ms: 30000

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  ai:
    mcp:
      server:
        name: sber-mcp-server
        protocol: STREAMABLE
        type: SYNC
        version: 1.0.0
        description: MCP сервер, для взаимодействия с инструментами, предоставляемыми Sber
        enabled: true
        sse:
          enabled: false
          path: /mcp/sse